name: Automated Preprocessing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn imblearn joblib

      # 4. Run preprocessing script
      - name: Run Preprocessing Script
        run: |
          python preprocessing/automate_Endang_Supriyadi.py

      # 5. Commit & push hasil preprocessing
      - name: Commit and Push Preprocessed Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USERNAME: ${{ secrets.USERNAME }}
          GIT_EMAIL: ${{ secrets.EMAIL }}
        run: |
          git config user.name "$GIT_USERNAME"
          git config user.email "$GIT_EMAIL"

          git add preprocessing/preprocessing_pipeline.joblib || true
          git add preprocessing/train_preprocessed.csv || true
          git add preprocessing/test_preprocessed.csv || true

          if ! git diff --cached --quiet; then
            git commit -m "Update preprocessed data"
            git push https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git
          else
            echo "No changes to commit"

      # 6. Upload hasil preprocessing sebagai artifact
      - name: Upload Preprocessed Files
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-data
          path: |
            preprocessing/preprocessing_pipeline.joblib
            preprocessing/train_preprocessed.csv
            preprocessing/test_preprocessed.csv
